// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flmainchain/fedlearning/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the fedlearning module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params             Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId             string            `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	CurrentRound       *CurrentRound     `protobuf:"bytes,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	RoundMap           []Round           `protobuf:"bytes,4,rep,name=round_map,json=roundMap,proto3" json:"round_map"`
	ModelSubmissionMap []ModelSubmission `protobuf:"bytes,5,rep,name=model_submission_map,json=modelSubmissionMap,proto3" json:"model_submission_map"`
	SubmittedScoreMap  []SubmittedScore  `protobuf:"bytes,6,rep,name=submitted_score_map,json=submittedScoreMap,proto3" json:"submitted_score_map"`
	FinalAttMap        []FinalAtt        `protobuf:"bytes,7,rep,name=final_att_map,json=finalAttMap,proto3" json:"final_att_map"`
	GlobalModelMap     []GlobalModel     `protobuf:"bytes,8,rep,name=global_model_map,json=globalModelMap,proto3" json:"global_model_map"`
	RoundCommitteeMap  []RoundCommittee  `protobuf:"bytes,9,rep,name=round_committee_map,json=roundCommitteeMap,proto3" json:"round_committee_map"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5774510bff650168, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetCurrentRound() *CurrentRound {
	if m != nil {
		return m.CurrentRound
	}
	return nil
}

func (m *GenesisState) GetRoundMap() []Round {
	if m != nil {
		return m.RoundMap
	}
	return nil
}

func (m *GenesisState) GetModelSubmissionMap() []ModelSubmission {
	if m != nil {
		return m.ModelSubmissionMap
	}
	return nil
}

func (m *GenesisState) GetSubmittedScoreMap() []SubmittedScore {
	if m != nil {
		return m.SubmittedScoreMap
	}
	return nil
}

func (m *GenesisState) GetFinalAttMap() []FinalAtt {
	if m != nil {
		return m.FinalAttMap
	}
	return nil
}

func (m *GenesisState) GetGlobalModelMap() []GlobalModel {
	if m != nil {
		return m.GlobalModelMap
	}
	return nil
}

func (m *GenesisState) GetRoundCommitteeMap() []RoundCommittee {
	if m != nil {
		return m.RoundCommitteeMap
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "flmainchain.fedlearning.v1.GenesisState")
}

func init() {
	proto.RegisterFile("flmainchain/fedlearning/v1/genesis.proto", fileDescriptor_5774510bff650168)
}

var fileDescriptor_5774510bff650168 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0xb6, 0x75, 0xab, 0xb7, 0x21, 0x16, 0x26, 0x51, 0xf5, 0x90, 0x95, 0x09, 0xb1,
	0xa8, 0x88, 0x84, 0x8e, 0x13, 0x47, 0x3a, 0x60, 0xe2, 0x50, 0x84, 0xd2, 0x03, 0x12, 0x97, 0xe0,
	0x26, 0x6e, 0xb0, 0x14, 0xdb, 0x91, 0xe3, 0x4e, 0xf0, 0x2d, 0xf8, 0x18, 0x1c, 0xf9, 0x18, 0x3b,
	0xee, 0x82, 0xc4, 0x09, 0xa1, 0xf6, 0xc0, 0xd7, 0x40, 0x7e, 0x71, 0x47, 0x52, 0x09, 0x8f, 0x4b,
	0x15, 0x3f, 0xfd, 0xff, 0xbf, 0xbf, 0xfd, 0x5e, 0x1f, 0xf2, 0x67, 0x39, 0xc3, 0x94, 0x27, 0x1f,
	0x31, 0xe5, 0xe1, 0x8c, 0xa4, 0x39, 0xc1, 0x92, 0x53, 0x9e, 0x85, 0x17, 0xc3, 0x30, 0x23, 0x9c,
	0x94, 0xb4, 0x0c, 0x0a, 0x29, 0x94, 0x70, 0x7b, 0x35, 0x65, 0x50, 0x53, 0x06, 0x17, 0xc3, 0xde,
	0x01, 0x66, 0x94, 0x8b, 0x10, 0x7e, 0x2b, 0x79, 0x2f, 0xb0, 0x80, 0x93, 0xb9, 0x94, 0x84, 0xab,
	0x58, 0x8a, 0x39, 0x4f, 0x8d, 0x7e, 0x60, 0xd1, 0xcf, 0x28, 0xc7, 0x79, 0x8c, 0x95, 0x32, 0xda,
	0xc7, 0xb6, 0x4b, 0xe7, 0x62, 0x8a, 0xf3, 0x98, 0x89, 0x94, 0xe4, 0x46, 0x3e, 0xb4, 0xc8, 0x41,
	0x17, 0x97, 0xf3, 0x29, 0xa3, 0x65, 0x49, 0x05, 0x37, 0x96, 0x13, 0x8b, 0xa5, 0xc0, 0x12, 0x33,
	0xd3, 0x95, 0xde, 0x43, 0x8b, 0xb0, 0xfe, 0xbc, 0x27, 0x37, 0xe9, 0xe2, 0x44, 0x30, 0x46, 0x95,
	0x22, 0xe4, 0x3f, 0x1c, 0x70, 0x5f, 0xa5, 0x48, 0x1a, 0x97, 0x89, 0x90, 0x2b, 0xc7, 0x61, 0x26,
	0x32, 0x01, 0x9f, 0xa1, 0xfe, 0xaa, 0xaa, 0xc7, 0xdf, 0xb7, 0xd0, 0xde, 0x79, 0x35, 0xc9, 0x89,
	0xc2, 0x8a, 0xb8, 0x2f, 0x51, 0xbb, 0x7a, 0x42, 0xd7, 0xe9, 0x3b, 0xfe, 0xee, 0xe9, 0x71, 0xf0,
	0xef, 0xc9, 0x06, 0x6f, 0x41, 0x39, 0xea, 0x5c, 0xfe, 0x3c, 0x6a, 0x7d, 0xfd, 0xfd, 0x6d, 0xe0,
	0x44, 0xc6, 0xec, 0xde, 0x43, 0xdb, 0x85, 0x90, 0x2a, 0xa6, 0x69, 0xf7, 0x56, 0xdf, 0xf1, 0x3b,
	0x51, 0x5b, 0x1f, 0x5f, 0xa7, 0xee, 0x18, 0xed, 0x37, 0x06, 0xdc, 0xdd, 0x80, 0x18, 0xdf, 0x16,
	0x73, 0x56, 0x19, 0x22, 0xad, 0x8f, 0xf6, 0x92, 0xda, 0xc9, 0x7d, 0x81, 0x3a, 0x55, 0x83, 0x18,
	0x2e, 0xba, 0x9b, 0xfd, 0x0d, 0x7f, 0xf7, 0xf4, 0xbe, 0x0d, 0x05, 0xae, 0xd1, 0xa6, 0xbe, 0x70,
	0xb4, 0x03, 0xce, 0x31, 0x2e, 0xdc, 0x04, 0x1d, 0xae, 0x8f, 0x1a, 0x80, 0x5b, 0x00, 0x7c, 0x64,
	0x03, 0x8e, 0xb5, 0x6f, 0x72, 0x6d, 0x33, 0x68, 0x97, 0x35, 0xcb, 0x3a, 0xe4, 0x03, 0xba, 0xbb,
	0x36, 0x19, 0xc8, 0x68, 0x43, 0xc6, 0xc0, 0x96, 0x31, 0x59, 0xd9, 0x26, 0xda, 0x65, 0x22, 0x0e,
	0xca, 0x46, 0x55, 0x27, 0xbc, 0x41, 0xfb, 0xd7, 0xcb, 0x00, 0xec, 0x6d, 0x60, 0x3f, 0xb0, 0xb1,
	0x5f, 0x69, 0xc3, 0x73, 0xa5, 0x0c, 0x75, 0x77, 0x66, 0xce, 0x9a, 0xf7, 0x0e, 0xdd, 0xa9, 0x2f,
	0x0c, 0x20, 0x77, 0x00, 0x79, 0x62, 0x43, 0x9e, 0x83, 0x07, 0x1a, 0x63, 0xa8, 0xb7, 0xb3, 0xbf,
	0x25, 0xd3, 0x8a, 0xb5, 0xbf, 0x35, 0xb0, 0x3b, 0x37, 0xb7, 0x02, 0xe6, 0x77, 0xb6, 0x72, 0xad,
	0x5a, 0x21, 0x1b, 0xd5, 0x31, 0x2e, 0x46, 0xcf, 0x2e, 0x17, 0x9e, 0x73, 0xb5, 0xf0, 0x9c, 0x5f,
	0x0b, 0xcf, 0xf9, 0xb2, 0xf4, 0x5a, 0x57, 0x4b, 0xaf, 0xf5, 0x63, 0xe9, 0xb5, 0xde, 0x1f, 0xd5,
	0x37, 0xe7, 0x53, 0x63, 0x77, 0xd4, 0xe7, 0x82, 0x94, 0xd3, 0x36, 0x6c, 0xc6, 0xd3, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0x26, 0x81, 0x81, 0xfd, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoundCommitteeMap) > 0 {
		for iNdEx := len(m.RoundCommitteeMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoundCommitteeMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.GlobalModelMap) > 0 {
		for iNdEx := len(m.GlobalModelMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GlobalModelMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.FinalAttMap) > 0 {
		for iNdEx := len(m.FinalAttMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FinalAttMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.SubmittedScoreMap) > 0 {
		for iNdEx := len(m.SubmittedScoreMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubmittedScoreMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ModelSubmissionMap) > 0 {
		for iNdEx := len(m.ModelSubmissionMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ModelSubmissionMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RoundMap) > 0 {
		for iNdEx := len(m.RoundMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoundMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CurrentRound != nil {
		{
			size, err := m.CurrentRound.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CurrentRound != nil {
		l = m.CurrentRound.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.RoundMap) > 0 {
		for _, e := range m.RoundMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ModelSubmissionMap) > 0 {
		for _, e := range m.ModelSubmissionMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SubmittedScoreMap) > 0 {
		for _, e := range m.SubmittedScoreMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FinalAttMap) > 0 {
		for _, e := range m.FinalAttMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GlobalModelMap) > 0 {
		for _, e := range m.GlobalModelMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RoundCommitteeMap) > 0 {
		for _, e := range m.RoundCommitteeMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentRound", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CurrentRound == nil {
				m.CurrentRound = &CurrentRound{}
			}
			if err := m.CurrentRound.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoundMap = append(m.RoundMap, Round{})
			if err := m.RoundMap[len(m.RoundMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelSubmissionMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelSubmissionMap = append(m.ModelSubmissionMap, ModelSubmission{})
			if err := m.ModelSubmissionMap[len(m.ModelSubmissionMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedScoreMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmittedScoreMap = append(m.SubmittedScoreMap, SubmittedScore{})
			if err := m.SubmittedScoreMap[len(m.SubmittedScoreMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalAttMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalAttMap = append(m.FinalAttMap, FinalAtt{})
			if err := m.FinalAttMap[len(m.FinalAttMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalModelMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalModelMap = append(m.GlobalModelMap, GlobalModel{})
			if err := m.GlobalModelMap[len(m.GlobalModelMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundCommitteeMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoundCommitteeMap = append(m.RoundCommitteeMap, RoundCommittee{})
			if err := m.RoundCommitteeMap[len(m.RoundCommitteeMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
