// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flmainchain/fedlearning/v1/model_submission.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ModelSubmission defines the ModelSubmission message.
type ModelSubmission struct {
	OriginalHash string `protobuf:"bytes,1,opt,name=original_hash,json=originalHash,proto3" json:"original_hash,omitempty"`
	Tag          string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Submitter    string `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty"`
}

func (m *ModelSubmission) Reset()         { *m = ModelSubmission{} }
func (m *ModelSubmission) String() string { return proto.CompactTextString(m) }
func (*ModelSubmission) ProtoMessage()    {}
func (*ModelSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aa730a06bba4d9a, []int{0}
}
func (m *ModelSubmission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModelSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModelSubmission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModelSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelSubmission.Merge(m, src)
}
func (m *ModelSubmission) XXX_Size() int {
	return m.Size()
}
func (m *ModelSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_ModelSubmission proto.InternalMessageInfo

func (m *ModelSubmission) GetOriginalHash() string {
	if m != nil {
		return m.OriginalHash
	}
	return ""
}

func (m *ModelSubmission) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ModelSubmission) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func init() {
	proto.RegisterType((*ModelSubmission)(nil), "flmainchain.fedlearning.v1.ModelSubmission")
}

func init() {
	proto.RegisterFile("flmainchain/fedlearning/v1/model_submission.proto", fileDescriptor_5aa730a06bba4d9a)
}

var fileDescriptor_5aa730a06bba4d9a = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcb, 0xc9, 0x4d,
	0xcc, 0xcc, 0x4b, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x4b, 0x4d, 0xc9, 0x49, 0x4d, 0x2c, 0xca,
	0xcb, 0xcc, 0x4b, 0xd7, 0x2f, 0x33, 0xd4, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0x89, 0x2f, 0x2e, 0x4d,
	0xca, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x42,
	0xd2, 0xa2, 0x87, 0xa4, 0x45, 0xaf, 0xcc, 0x50, 0x29, 0x8d, 0x8b, 0xdf, 0x17, 0xa4, 0x2b, 0x18,
	0xae, 0x49, 0x48, 0x99, 0x8b, 0x37, 0xbf, 0x28, 0x33, 0x3d, 0x33, 0x2f, 0x31, 0x27, 0x3e, 0x23,
	0xb1, 0x38, 0x43, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x07, 0x26, 0xe8, 0x91, 0x58, 0x9c,
	0x21, 0x24, 0xc0, 0xc5, 0x5c, 0x92, 0x98, 0x2e, 0xc1, 0x04, 0x96, 0x02, 0x31, 0x85, 0x64, 0xb8,
	0x38, 0xc1, 0x36, 0x97, 0x94, 0xa4, 0x16, 0x49, 0x30, 0x83, 0xc5, 0x11, 0x02, 0x4e, 0x96, 0x27,
	0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c,
	0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0x25, 0x8f, 0xec, 0xa1, 0x0a, 0x14, 0x2f,
	0x95, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x7d, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xd1, 0x21, 0x3f, 0xfa, 0x00, 0x00, 0x00,
}

func (m *ModelSubmission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModelSubmission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ModelSubmission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintModelSubmission(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintModelSubmission(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OriginalHash) > 0 {
		i -= len(m.OriginalHash)
		copy(dAtA[i:], m.OriginalHash)
		i = encodeVarintModelSubmission(dAtA, i, uint64(len(m.OriginalHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModelSubmission(dAtA []byte, offset int, v uint64) int {
	offset -= sovModelSubmission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ModelSubmission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OriginalHash)
	if l > 0 {
		n += 1 + l + sovModelSubmission(uint64(l))
	}
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovModelSubmission(uint64(l))
	}
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovModelSubmission(uint64(l))
	}
	return n
}

func sovModelSubmission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModelSubmission(x uint64) (n int) {
	return sovModelSubmission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ModelSubmission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModelSubmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModelSubmission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModelSubmission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelSubmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelSubmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelSubmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelSubmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelSubmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelSubmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelSubmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelSubmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelSubmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModelSubmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModelSubmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModelSubmission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModelSubmission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModelSubmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModelSubmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModelSubmission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModelSubmission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModelSubmission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModelSubmission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModelSubmission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModelSubmission = fmt.Errorf("proto: unexpected end of group")
)
